/** Auto-generated from public/assets/Leagues — do not edit by hand. */
export const LEAGUE_LOGO_FILES = [
  "1 Lig",
  "1. Divisjon",
  "1. HNL",
  "1st Division",
  "2 Liga",
  "A Lyga",
  "A-League",
  "A-League Women",
  "ABA League",
  "AFC Asian Cup Women",
  "AFC Asian Cup Women Qualifiers",
  "AFC Champions League",
  "AFL",
  "ATP Challenger",
  "ATP Events",
  "Algeria Ligue 1",
  "Allsvenskan",
  "Argentina Copa Argentina",
  "Argentina LNB",
  "Argentina Liga Argentina",
  "Argentina Liga Argentina Women",
  "Argentina Primera Division",
  "Argentina Primera Nacional",
  "Australia A-League",
  "Australia A-League Women",
  "Australia Big Bash League",
  "Australia Big Bash League Women",
  "Australia NBL",
  "Australia NRL",
  "Austria 2 Liga",
  "Austria AVL",
  "Austria BSL",
  "Austria Bundesliga",
  "Austria Ice Hockey League",
  "Austria WVL",
  "BIG3",
  "Belarus Extraliga",
  "Belarus Premier League",
  "Belgium Challenger Pro League",
  "Belgium Liga Dames",
  "Belgium Liga Heren",
  "Belgium Pro League",
  "Besta Deild Karla",
  "Boxing",
  "Boxing Non Title",
  "Brazil Serie A",
  "Brazil Serie B",
  "Brazil Superliga",
  "Brazil Superliga Women",
  "Bulgaria Parva Liga",
  "Bundesliga",
  "Bundesliga 2",
  "Bundesliga 3",
  "Bundesliga Futures",
  "CAF Africa Cup of Nations",
  "CAF Africa Cup of Nations Futures",
  "CEV Champions League",
  "CEV Champions League Women",
  "CEV Cup",
  "CEV Cup Women",
  "CFL",
  "CONCACAF Champions Cup",
  "CONCACAF Champions Cup Women",
  "CONCACAF Championship Women",
  "CONCACAF Gold Cup",
  "CONCACAF Nations League",
  "CONCACAF Qualifiers Championship Women",
  "CONMEBOL Copa Sudamericana",
  "CONMEBOL WC Qualification",
  "CPBL",
  "CS2",
  "Call of Duty",
  "Canada OHL",
  "Canada QMJHL",
  "Canada WHL",
  "Challenge League",
  "Challenger Pro League",
  "Champions Hockey League",
  "Championship",
  "Chile Primera Division",
  "China CBA",
  "China CVL",
  "China CVL - Copy Women",
  "China Super League",
  "College Baseball",
  "Colombia Primera A",
  "Community Shield",
  "Copa Argentina",
  "Copa Libertadores",
  "Copa del Rey",
  "Copa do Brasil",
  "Coppa Italia",
  "Costa Rica Primera Division",
  "Coupe de France",
  "Croatia 1. HNL",
  "Croatia HB Premijer Liga",
  "Crossfire",
  "Cup",
  "Cupa Romaniei",
  "Cymru Premier",
  "Cyprus First Division",
  "Czech Republic Extraliga",
  "Czech Republic First League",
  "Czech Republic VEL",
  "Czech Republic VEL Women",
  "DBU Pokalen",
  "DFB Pokal",
  "DOTA 2",
  "Davis Cup",
  "Denmark 1st Division",
  "Denmark DBU Pokalen",
  "Denmark Superisligaen",
  "Denmark Superliga",
  "Denmark Volleyligaen",
  "Denmark Volleyligaen Women",
  "Division 1",
  "Division Professional",
  "EFL Championship",
  "EFL Cup",
  "EHF Champions League",
  "EHF Champions League Women",
  "EHF European Championship",
  "EHF European League",
  "EPL",
  "EPL Futures",
  "ESPORTS",
  "Ecuador Serie A",
  "Eerste Divisie",
  "Egypt Premier League",
  "Ekstraklasa",
  "Eliteserien",
  "Emperor Cup",
  "England League 1",
  "England League 2",
  "England Premier League Darts",
  "England Premier League Darts - Copy",
  "England Premier League Darts Futures",
  "England Super League",
  "Eredivisie",
  "Eredivisie Women",
  "Erovnuli Liga",
  "Eurocup",
  "Euroleague",
  "Euroleague Futures",
  "Euroleague Women",
  "FA Cup",
  "FIBA AfroBasket",
  "FIBA AfroBasket Qualifiers",
  "FIBA Americup",
  "FIBA Americup Qualifiers",
  "FIBA Americup Women",
  "FIBA Asia Cup Qualifiers",
  "FIBA Champions League",
  "FIBA EuroBasket",
  "FIBA EuroBasket Futures",
  "FIBA Eurobasket Qualifiers",
  "FIBA Eurobasket Women",
  "FIBA Europe Cup",
  "FIBA World Cup Qualifiers",
  "FIBA World Cup U19",
  "FIFA Arab Nations Cup",
  "FIFA Club World Cup",
  "FIFA Intercontinental Cup",
  "FIFA World Cup",
  "FIFA World Cup Futures",
  "FIFA World Cup Qualifiers",
  "FIFA World Cup U20",
  "FINA World Championship",
  "FINA World Championship Women",
  "FIVB Nations League",
  "FIVB Nations League Women",
  "FIVB World Championship",
  "FIVB World Championship Women",
  "FNL",
  "FUTURES",
  "Finland Korisliiga",
  "Finland Mestaruusliiga",
  "Finland Mestaruusliiga Women",
  "Finland SM Liiga",
  "First Division",
  "First League",
  "Formula 1 Futures",
  "France LNB Pro A",
  "France LNH Division 1",
  "France Ligue A",
  "France Ligue A Women",
  "France Ligue Magnus",
  "Frauen Bundesliga",
  "GOLF",
  "Germany 1st Bundesliga",
  "Germany 1st Bundesliga Women",
  "Germany BBL",
  "Germany Bundesliga 3",
  "Germany DEL",
  "Germany Frauen Bundesliga",
  "Germany HBL",
  "Grand Slam",
  "Greece A1 League",
  "Greece Super League",
  "Hungary HNB I",
  "Hungary NB I",
  "ICC T20 World Cup",
  "IHF World Championship",
  "IIHF World Championship",
  "ITF Men",
  "ITF Women",
  "Iceland Urvalsdeild",
  "Indian Premier League",
  "Indonesia Liga 1",
  "IndyCar Futures",
  "International Club Friendlies",
  "International Friendlies",
  "International Friendlies Women",
  "International T20 Matches",
  "Iran Super League",
  "Ireland Division 1",
  "Ireland Premier League",
  "Israel Super League",
  "Italy Coppa Italia A1 Women",
  "Italy Coppa Italia Superlega",
  "Italy Lega Basket Serie A",
  "Italy Serie A1 Women",
  "Italy Serie A2",
  "Italy Serie C",
  "Italy Superlega",
  "J1 League",
  "Japan SV League",
  "Japan SV League Women",
  "KBO",
  "KNVB Beker",
  "Kazakhstan Premier League",
  "Kings of Glory",
  "Korea K1 League",
  "Korea K2 League",
  "Korea KBL",
  "Korea WKBL",
  "LEN European Championship",
  "LOL",
  "La Liga",
  "La Liga 2",
  "La Liga Futures",
  "Latvia Hockey League",
  "Latvia Virsliga",
  "League 1",
  "League 2",
  "League Cup",
  "Liga 1",
  "Liga 3",
  "Liga F Women",
  "Liga I",
  "Liga II",
  "Liga MX",
  "Liga de Expansion MX",
  "Ligue 1",
  "Ligue 1 Futures",
  "Ligue 2",
  "Lithuania A Lyga",
  "MLB",
  "MLB All Star",
  "MLB Futures",
  "MLS",
  "MOTOSPORT",
  "Malta Premier League",
  "Mexico LMB",
  "Mexico Liga MX Women",
  "Mobile Legends",
  "NASCAR Cup Series Futures",
  "NB I",
  "NBA",
  "NBA All Star",
  "NBA Futures",
  "NBA Summer League",
  "NCAA Basketball",
  "NCAA Lacrosse",
  "NCAAB Futures",
  "NCAAF Futures",
  "NCAAH",
  "NCAAW",
  "NCCA Basketball",
  "NHL",
  "NHL Futures",
  "NM Cup",
  "NPB",
  "NWSL",
  "National Lacrosse League",
  "Netherlands Eerste Divisie",
  "Netherlands KNVB Beker",
  "North America Leagues Cup",
  "North Macedonia Super Liga",
  "Northern Ireland Premiership",
  "Norway BLNO",
  "Norway BLNOO",
  "Norway Elitehockeyligaen",
  "Norway HB 1. Divisjon",
  "Norway NM Cup",
  "Norway NVBF",
  "OFB Cup",
  "Olympics Curling Men",
  "Olympics Curling Mixed",
  "Olympics Curling Women",
  "Olympics Hockey Men",
  "Olympics Hockey Women",
  "Open Cup",
  "Overwatch",
  "PBA Philippine Cup",
  "PDC European Darts Championship",
  "PDC European Tour",
  "PDC Grand Slam of Darts",
  "PDC Players Championship",
  "PDC World Championship",
  "PDC World Cup of Darts",
  "PDC World Grand Prix",
  "PDC World Matchplay",
  "PDC World Matchplay Women",
  "PDC World Series Of Darts",
  "PFL",
  "PGA Futures",
  "Pakistan Super League",
  "Paraguay Primera Division",
  "Parva Liga",
  "Peru Primera Division",
  "Philippines PVL Women",
  "Poland Ekstraklasa",
  "Poland PKL",
  "Poland PlusLiga",
  "Poland Polska Hokej Liga",
  "Poland Superliga",
  "Portugal Segunda Liga",
  "Premier Lacrosse League",
  "Premier League",
  "Premiere Ligue Women",
  "Premiership",
  "Premium Liiga",
  "Primeira Liga",
  "Primera A",
  "Primera Division",
  "Primera Federacion",
  "Primera Nacional",
  "Pro League",
  "PrvaLiga",
  "Rainbow Six Siege",
  "Rocket League",
  "Romania Liga I",
  "Russia Cup",
  "Russia First League",
  "Russia KHL",
  "Russia Premier League",
  "Russia Super League",
  "Russia Superliga",
  "Russia Superliga Women",
  "Saudi Professional League",
  "Scotland Championship",
  "Scotland Premiership",
  "Segunda Liga",
  "Serbia Super Liga",
  "Serbia Superliga",
  "Serie A",
  "Serie A Femminile",
  "Serie A Futures",
  "Serie B",
  "Serie C",
  "Singapore NBL",
  "Singapore Premier League",
  "Six Nations",
  "Slovakia HB Extraliga",
  "Slovakia Superliga",
  "Slovenia 1. Liga",
  "Slovenia PrvaLiga",
  "South Africa Premier League",
  "South Korea V League",
  "South Korea V League Women",
  "Spain ASOBAL",
  "Spain Liga ACB",
  "Spain Primera Federacion",
  "Starcraft",
  "Starcraft 2",
  "Stars League",
  "Summer Olympics Water Polo",
  "Super League",
  "Super Lig",
  "Super Liga",
  "Super Rugby",
  "Superettan",
  "Superliga",
  "Sweden BasketLigaen",
  "Sweden Handbollsligan",
  "Sweden SHL",
  "Switzerland Challenge League",
  "Switzerland National League",
  "Switzerland Super League",
  "T20 Blast",
  "Taca de Portugal",
  "Thai League 1",
  "Turkey 1 Lig",
  "Turkey BSL",
  "Turkey Super Lig",
  "UAE Pro League",
  "UEFA Champions League",
  "UEFA Champions League Futures",
  "UEFA Champions League Qualification",
  "UEFA Champions League Women",
  "UEFA Conference League",
  "UEFA Conference League Qualification",
  "UEFA Europa League",
  "UEFA Europa League Qualification",
  "UEFA European Championship Qualifiers U19",
  "UEFA European Championship Qualifiers U21",
  "UEFA European Championship U21",
  "UEFA European Championship Women",
  "UEFA Nations League",
  "UEFA Nations League Women",
  "UEFA Super Cup",
  "UFC",
  "US Election 2024",
  "USA AHL",
  "USA Major League Cricket",
  "USA NWSL",
  "USA Open Cup",
  "USA The Golf League",
  "USA USL Championship",
  "USL Championship",
  "Ukraine Premier League",
  "United Cup",
  "Uruguay Primera Division",
  "Uzbekistan Super League",
  "V League 1",
  "VTB United League",
  "Valorant",
  "Veikkausliiga",
  "Vietnam V League 1",
  "Virsliga",
  "WAFF Championship Women",
  "WNBA",
  "WTA Events",
  "Wales Cymru Premier",
  "Women's Super League",
  "World Baseball Classic",
  "Ykkösliiga",
  "eBasketball Valhalla",
  "eFootball Valhalla"
] as const
